DELETE FROM company_trainingcurriculumexam;
UPDATE sqlite_sequence SET seq = 0 WHERE name = 'company_trainingcurriculumexam';
DELETE FROM company_corporateattendingstudentcurriculum;
UPDATE sqlite_sequence SET seq = 0 WHERE name = 'company_corporateattendingstudentcurriculum';
DELETE FROM company_groupcurriculum;
UPDATE sqlite_sequence SET seq = 0 WHERE name = 'company_groupcurriculum';
DELETE FROM company_groupstudent;
UPDATE sqlite_sequence SET seq = 0 WHERE name = 'company_groupstudent';
DELETE FROM company_trainingcurriculumcourse;
UPDATE sqlite_sequence SET seq = 0 WHERE name = 'company_trainingcurriculumcourse';
DELETE FROM company_trainingcurriculum;
UPDATE sqlite_sequence SET seq = 0 WHERE name = 'company_trainingcurriculum';
DELETE FROM company_group;
UPDATE sqlite_sequence SET seq = 0 WHERE name = 'company_group';
DELETE FROM company_corporateattendingstudent;
DELETE FROM company_company;
UPDATE sqlite_sequence SET seq = 0 WHERE name = 'company_company';
DELETE FROM student_comment;
UPDATE sqlite_sequence SET seq = 0 WHERE name = 'student_comment';
DELETE FROM student_question;
UPDATE sqlite_sequence SET seq = 0 WHERE name = 'student_question';
DELETE FROM student_examresulthistory;
UPDATE sqlite_sequence SET seq = 0 WHERE name = 'student_examresulthistory';
DELETE FROM student_examresultdetail;
UPDATE sqlite_sequence SET seq = 0 WHERE name = 'student_examresultdetail';
DELETE FROM student_examresult;
DELETE FROM student_contentattending;
UPDATE sqlite_sequence SET seq = 0 WHERE name = 'student_contentattending';
DELETE FROM student_sectionattending;
UPDATE sqlite_sequence SET seq = 0 WHERE name = 'student_sectionattending';
DELETE FROM student_courseattending;
UPDATE sqlite_sequence SET seq = 0 WHERE name = 'student_courseattending';
DELETE FROM student_coursepurchase;
UPDATE sqlite_sequence SET seq = 0 WHERE name = 'student_coursepurchase';
DELETE FROM online_learning_platform_student;
DELETE FROM teacher_coupon;
UPDATE sqlite_sequence SET seq = 0 WHERE name = 'teacher_coupon';
DELETE FROM teacher_examquestionchoice;
UPDATE sqlite_sequence SET seq = 0 WHERE name = 'teacher_examquestionchoice';
DELETE FROM teacher_examquestion;
UPDATE sqlite_sequence SET seq = 0 WHERE name = 'teacher_examquestion';
DELETE FROM teacher_examination;
DELETE FROM teacher_lecturevideo;
DELETE FROM teacher_content;
UPDATE sqlite_sequence SET seq = 0 WHERE name = 'teacher_content';
DELETE FROM teacher_section;
UPDATE sqlite_sequence SET seq = 0 WHERE name = 'teacher_section';
DELETE FROM teacher_course;
UPDATE sqlite_sequence SET seq = 0 WHERE name = 'teacher_course';
DELETE FROM online_learning_platform_teacher;
DELETE FROM online_learning_platform_account;
DELETE FROM auth_user;
UPDATE sqlite_sequence SET seq = 0 WHERE name = 'auth_user';
