COPY WebPage1.html trainingcurriculumcourse_form.html
COPY WebPage1.html groupstudent_form.html
COPY WebPage1.html groupcurriculum_form.html
COPY WebPage1.html corporateattendingstudentcurriculum_form.html
COPY WebPage1.html trainingcurriculumexam_form.html
COPY WebPage1.html trainingcurriculumcourse_detail.html
COPY WebPage1.html groupstudent_detail.html
COPY WebPage1.html groupcurriculum_detail.html
COPY WebPage1.html corporateattendingstudentcurriculum_detail.html
COPY WebPage1.html trainingcurriculumexam_detail.html
COPY WebPage1.html trainingcurriculumcourse_confirm_delete.html
COPY WebPage1.html groupstudent_confirm_delete.html
COPY WebPage1.html groupcurriculum_confirm_delete.html
COPY WebPage1.html corporateattendingstudentcurriculum_confirm_delete.html
COPY WebPage1.html trainingcurriculumexam_confirm_delete.html

