# Generated by Django 5.0.6 on 2025-01-28 06:56

import django.contrib.auth.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("company", "0001_initial"),
        ("online_learning_platform", "0001_initial"),
        ("teacher", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CorporateAttendingStudent",
            fields=[
                (
                    "student_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="online_learning_platform.student",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="company.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            bases=("online_learning_platform.student",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("group_no", models.IntegerField()),
                (
                    "group_name",
                    models.CharField(max_length=15, verbose_name="グループ名"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="company.company",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GroupStudent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="company.group"
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="company.corporateattendingstudent",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="group",
            name="students",
            field=models.ManyToManyField(
                through="company.GroupStudent",
                to="company.corporateattendingstudent",
                verbose_name="法人受講生",
            ),
        ),
        migrations.CreateModel(
            name="TrainingCurriculum",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("training_curriculum_no", models.IntegerField()),
                (
                    "training_curriculum_name",
                    models.CharField(max_length=15, verbose_name="研修カリキュラム名"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="company.company",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GroupCurriculum",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_startable_attending",
                    models.DateField(verbose_name="受講開始可能年月日"),
                ),
                (
                    "attending_complete_deadline_date",
                    models.DateField(verbose_name="受講完了期限年月日"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="company.group"
                    ),
                ),
                (
                    "curriculum",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="company.trainingcurriculum",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="group",
            name="curriculums",
            field=models.ManyToManyField(
                through="company.GroupCurriculum",
                to="company.trainingcurriculum",
                verbose_name="研修カリキュラム",
            ),
        ),
        migrations.CreateModel(
            name="CorporateAttendingStudentCurriculum",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "training_curriculum_attending_start_time",
                    models.DateTimeField(auto_now_add=True),
                ),
                (
                    "training_curriculum_attending_complete_time",
                    models.DateTimeField(null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="company.corporateattendingstudent",
                    ),
                ),
                (
                    "curriculum",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="company.trainingcurriculum",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="corporateattendingstudent",
            name="curriculums",
            field=models.ManyToManyField(
                through="company.CorporateAttendingStudentCurriculum",
                to="company.trainingcurriculum",
                verbose_name="研修カリキュラム",
            ),
        ),
        migrations.CreateModel(
            name="TrainingCurriculumCourse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attending_order", models.IntegerField(verbose_name="受講順")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="teacher.course",
                    ),
                ),
                (
                    "curriculum",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="company.trainingcurriculum",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="trainingcurriculum",
            name="courses",
            field=models.ManyToManyField(
                through="company.TrainingCurriculumCourse",
                to="teacher.course",
                verbose_name="コース",
            ),
        ),
        migrations.CreateModel(
            name="TrainingCurriculumExam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("passing_base_point", models.IntegerField(verbose_name="合格基準点")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "curriculum",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="company.trainingcurriculum",
                    ),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="teacher.examination",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="trainingcurriculum",
            name="exams",
            field=models.ManyToManyField(
                through="company.TrainingCurriculumExam",
                to="teacher.examination",
                verbose_name="テスト",
            ),
        ),
        migrations.AddConstraint(
            model_name="groupstudent",
            constraint=models.UniqueConstraint(
                fields=("group", "student"), name="unique_groupstudent"
            ),
        ),
        migrations.AddConstraint(
            model_name="groupcurriculum",
            constraint=models.UniqueConstraint(
                fields=("group", "curriculum"), name="unique_groupcurriculum"
            ),
        ),
        migrations.AddConstraint(
            model_name="group",
            constraint=models.UniqueConstraint(
                fields=("company", "group_no"), name="unique_group"
            ),
        ),
        migrations.AddConstraint(
            model_name="corporateattendingstudentcurriculum",
            constraint=models.UniqueConstraint(
                fields=("student", "curriculum"), name="unique_studentcurriculum"
            ),
        ),
        migrations.AddConstraint(
            model_name="trainingcurriculumcourse",
            constraint=models.UniqueConstraint(
                fields=("curriculum", "course"), name="unique_curriculumcourse"
            ),
        ),
        migrations.AddConstraint(
            model_name="trainingcurriculumexam",
            constraint=models.UniqueConstraint(
                fields=("curriculum", "exam"), name="unique_curriculumexam"
            ),
        ),
        migrations.AddConstraint(
            model_name="trainingcurriculum",
            constraint=models.UniqueConstraint(
                fields=("company", "training_curriculum_no"),
                name="unique_training_curriculum",
            ),
        ),
    ]
