# Generated by Django 5.0.6 on 2025-01-31 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0002_initial"),
        ("teacher", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="corporateattendingstudent",
            name="curriculums",
            field=models.ManyToManyField(
                related_name="corporate_attending_student",
                through="company.CorporateAttendingStudentCurriculum",
                to="company.trainingcurriculum",
                verbose_name="研修カリキュラム",
            ),
        ),
        migrations.AddConstraint(
            model_name="trainingcurriculumcourse",
            constraint=models.UniqueConstraint(
                fields=("curriculum", "attending_order"),
                name="unique_curriculumcourse_order",
            ),
        ),
    ]
