from django.urls import path
from . import views

app_name = "company"
urlpatterns = [
    path("", views.CompanyListView.as_view(), name="index"),
    path("create/", views.CompanyCreateView.as_view(), name="company-create"),
    path("<int:pk>/update/", views.CompanyUpdateView.as_view(), name="company-update"),
    path("<int:pk>/delete/", views.CompanyDeleteView.as_view(), name="company-delete"),
    path("<int:pk>/", views.CompanyDetailView.as_view(), name="company-detail"),
    path(
        "corporate_attending_student/create/",
        views.CorporateAttendingStudentCreateView.as_view(),
        name="corporate_attending_student-create",
    ),
    path(
        "corporate_attending_student/<int:pk>/update/",
        views.CorporateAttendingStudentUpdateView.as_view(),
        name="corporate_attending_student-update",
    ),
    path(
        "corporate_attending_student/<int:pk>/delete/",
        views.CorporateAttendingStudentDeleteView.as_view(),
        name="corporate_attending_student-delete",
    ),
    path(
        "corporate_attending_student/<int:pk>/",
        views.CorporateAttendingStudentDetailView.as_view(),
        name="corporate_attending_student-detail",
    ),
    path("group/create/", views.GroupCreateView.as_view(), name="group-create"),
    path(
        "group/<int:pk>/update/", views.GroupUpdateView.as_view(), name="group-update"
    ),
    path(
        "group/<int:pk>/delete/", views.GroupDeleteView.as_view(), name="group-delete"
    ),
    path("group/<int:pk>/", views.GroupDetailView.as_view(), name="group-detail"),
    path(
        "training_curriculum/create/",
        views.TrainingCurriculumCreateView.as_view(),
        name="training_curriculum-create",
    ),
    path(
        "training_curriculum/<int:pk>/update/",
        views.TrainingCurriculumUpdateView.as_view(),
        name="training_curriculum-update",
    ),
    path(
        "training_curriculum/<int:pk>/delete/",
        views.TrainingCurriculumDeleteView.as_view(),
        name="training_curriculum-delete",
    ),
    path(
        "training_curriculum/<int:pk>/",
        views.TrainingCurriculumDetailView.as_view(),
        name="training_curriculum-detail",
    ),
    path(
        "curriculum_course/create/",
        views.CurriculumCourseCreateView.as_view(),
        name="curriculum_course-create",
    ),
    path(
        "curriculum_course/<int:pk>/update/",
        views.CurriculumCourseUpdateView.as_view(),
        name="curriculum_course-update",
    ),
    path(
        "curriculum_course/<int:pk>/delete/",
        views.CurriculumCourseDeleteView.as_view(),
        name="curriculum_course-delete",
    ),
    path(
        "curriculum_course/<int:pk>/",
        views.CurriculumCourseDetailView.as_view(),
        name="curriculum_course-detail",
    ),
    path(
        "group_student/create/",
        views.GroupStudentCreateView.as_view(),
        name="group_student-create",
    ),
    path(
        "group_student/<int:pk>/update/",
        views.GroupStudentUpdateView.as_view(),
        name="group_student-update",
    ),
    path(
        "group_student/<int:pk>/delete/",
        views.GroupStudentDeleteView.as_view(),
        name="group_student-delete",
    ),
    path(
        "group_student/<int:pk>/",
        views.GroupStudentDetailView.as_view(),
        name="group_student-detail",
    ),
    path(
        "group_curriculum/create/",
        views.GroupCurriculumCreateView.as_view(),
        name="group_curriculum-create",
    ),
    path(
        "curriculum_group/create/",
        views.CurriculumGroupCreateView.as_view(),
        name="curriculum_group-create",
    ),
    path(
        "group_curriculum/<int:pk>/update/",
        views.GroupCurriculumUpdateView.as_view(),
        name="group_curriculum-update",
    ),
    path(
        "group_curriculum/<int:pk>/delete/",
        views.GroupCurriculumDeleteView.as_view(),
        name="group_curriculum-delete",
    ),
    path(
        "curriculum_group/<int:pk>/delete/",
        views.CurriculumGroupDeleteView.as_view(),
        name="curriculum_group-delete",
    ),
    path(
        "group_curriculum/<int:pk>/",
        views.GroupCurriculumDetailView.as_view(),
        name="group_curriculum-detail",
    ),
    path(
        "student_curriculum/create/",
        views.StudentCurriculumCreateView.as_view(),
        name="student_curriculum-create",
    ),
    path(
        "student_curriculum/<int:pk>/update/",
        views.StudentCurriculumUpdateView.as_view(),
        name="student_curriculum-update",
    ),
    path(
        "student_curriculum/<int:pk>/delete/",
        views.StudentCurriculumDeleteView.as_view(),
        name="student_curriculum-delete",
    ),
    path(
        "student_curriculum/<int:pk>/",
        views.StudentCurriculumDetailView.as_view(),
        name="student_curriculum-detail",
    ),
    path(
        "curriculum_exam/create/",
        views.CurriculumExamCreateView.as_view(),
        name="curriculum_exam-create",
    ),
    path(
        "curriculum_exam/<int:pk>/update/",
        views.CurriculumExamUpdateView.as_view(),
        name="curriculum_exam-update",
    ),
    path(
        "curriculum_exam/<int:pk>/delete/",
        views.CurriculumExamDeleteView.as_view(),
        name="curriculum_exam-delete",
    ),
    path(
        "curriculum_exam/<int:pk>/",
        views.CurriculumExamDetailView.as_view(),
        name="curriculum_exam-detail",
    ),
]